twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        listData: '@App\Service\ListData'
        access:   '@App\Service\Access'

when@test:
    twig:
        strict_variables: true
